services:
  inmediam_db:
    image: "postgres"
    ports:
      - "54320:5432"
    container_name: inmediam-db
    restart: always
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
    volumes:
      - db:/var/lib/postgresql/data

  inmediam_db_testing:
    image: "postgres"
    ports:
      - "54321:5432"
    container_name: inmediam-db-testing
    restart: always
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
    volumes:
      - db:/var/lib/postgresql_testing/data

volumes:
  db:
    driver: local